name: slate_runner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run FastAPI with Uvicorn
        env:
          API_HOST: "127.0.0.1"
          API_PORT: "8000"
          LOG_LEVEL: "info"
        run: |
          python -m uvicorn main:api --app-dir src --host $API_HOST --port $API_PORT --reload &
          sleep 5  # Give the server a few seconds to boot up
          curl http://$API_HOST:$API_PORT/api/healthz

      - name: Run tests (if any)
        run: |
          pytest || echo "No tests yet, skipping"
