name: slate_runner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8 (strict mode)
        run: |
          source .venv/bin/activate
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint with flake8 (full mode)
        run: |
          source .venv/bin/activate
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Start FastAPI with Uvicorn in background
        run: |
            source .venv/bin/activate
            cd src
            python -m uvicorn main:app --host 127.0.0.1 --port 8000 --log-level info > ../uvicorn.log 2>&1 &
            echo $! > ../uvicorn.pid
            cd ..
            sleep 5
            cat uvicorn.log

      - name: Health check API
        run: |
          curl -f http://127.0.0.1:8000/api/healthz || (echo "API did not start or is unreachable" && exit 1)

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest || echo "No tests yet, skipping"

      - name: Stop Uvicorn server
        run: |
          kill $(cat uvicorn.pid)
